In [1]:
import pandas as pd
import numpy as np
import requests as req
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time
from IPython.display import Image

In [2]:
path= ChromeDriverManager().install()
driver= webdriver.Chrome(path)

C:\Users\USER\AppData\Local\Temp\ipykernel_5960\1621371287.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver= webdriver.Chrome(path)

In [3]:
url='https://www.imdb.com/list/ls552103190/'
driver.get(url)

In [4]:
directores=[]
urls=[]
fotos=[]

for i in range(2):
    
    nombres= driver.find_elements('xpath', '//h3[@class="lister-item-header"]/a')
    for nombre in nombres:
        directores.append(nombre.text)
    
    direcciones= driver.find_elements('xpath', '//h3[@class="lister-item-header"]/a')
    for direccion in direcciones:
        urls.append(direccion.get_attribute('href'))
    
    imagenes= driver.find_elements('xpath', '//div[@class="lister-item-image"]/a/img')
    for imagen in imagenes:
        fotos.append(imagen.get_attribute('src'))
    
    try:
        driver.find_element('xpath', '//a[@class="flat-button lister-page-next next-page"]').click()
        time.sleep(7)
    except:
        break

In [5]:
len(fotos)

114

In [16]:
display(Image(url=fotos[112]))

In [6]:
columnas=['directores', 'fotos', 'urls']
linkdirectores= pd.DataFrame(list(zip(directores,urls,fotos)), columns=columnas)
linkdirectores.tail()

,directores,fotos,urls
109,Carlos Vermut,https://www.imdb.com/name/nm4209430?ref_=nmls_hd,https://m.media-amazon.com/images/M/MV5BMjhjOT...
110,Carla Simón,https://www.imdb.com/name/nm3427032?ref_=nmls_hd,https://m.media-amazon.com/images/M/MV5BYjIzZW...
111,Raúl Arévalo,https://www.imdb.com/name/nm1666855?ref_=nmls_hd,https://m.media-amazon.com/images/M/MV5BYjZkZD...
112,Pilar Palomero,https://www.imdb.com/name/nm1970178?ref_=nmls_hd,https://m.media-amazon.com/images/M/MV5BYTkwOG...
113,Borja Soler,https://www.imdb.com/name/nm2111339?ref_=nmls_hd,https://m.media-amazon.com/images/S/sash/9FayP...

In [17]:
linkdirectores.to_csv(r'C:\Users\USER\Documents\Lucía\Ironhack\Bootcamp\Proyecto_final\linksdirectores.csv', index=False)

In [15]:
nombres=[]
urls2=[]
premios=[]
generos1=[]
generos2=[]

for url in urls:
    driver.get(url)
    urls2.append(url)
    
    direct= driver.find_element('xpath', '//h1[@data-testid="hero__pageTitle"]/span[1]').text
    nombres.append(direct)
    
    try:
        nominaciones= driver.find_element('xpath', '//div[@class="ipc-metadata-list-item__content-container"]/ul/li/label').text
    except:
        nominaciones=''
    premios.append(nominaciones)
        
    driver.find_element('xpath', '//button[@data-testid="hero-subnav-bar-all-topics-button"]').click()
    time.sleep(3)
    driver.find_element('xpath', '//a[text()="por género"]').click()
    time.sleep(3)
        
    try:
        cat1= driver.find_element('xpath', '//div[@class="faceter-fieldset genres"]/fieldset/span[1]').text
    except:
        cat1=''
    
    try:
        cat2= driver.find_element('xpath', '//div[@class="faceter-fieldset genres"]/fieldset/span[2]').text
    except:
        cat2=''
        
    generos1.append(cat1)
    generos2.append(cat2)

In [16]:
premios[2]

'31 premios y 28 nominaciones'

In [17]:
columnas= ['directores', 'premios', 'generos1', 'generos2', 'urls2']
generosdirectores= pd.DataFrame(list(zip(nombres,premios,generos1,generos2,urls2)), columns=columnas)
generosdirectores.head(20)

,directores,premios,generos1,generos2,urls2
0,Achero Mañas,26 premios y 7 nominaciones,Comedy (74),Drama (24),https://www.imdb.com/name/nm0563748?ref_=nmls_hd
1,Alejandro Amenábar,61 premios y 56 nominaciones en total,News (61),Talk-Show (35),https://www.imdb.com/name/nm0024622?ref_=nmls_hd
2,J.A. Bayona,31 premios y 28 nominaciones,News (55),Documentary (46),https://www.imdb.com/name/nm1291105?ref_=nmls_hd
3,Juan Antonio Bardem,21 premios y 9 nominaciones,Drama (36),Documentary (23),https://www.imdb.com/name/nm0054219?ref_=nmls_hd
4,Jaume Collet-Serra,5 nominaciones,Thriller (25),Action (18),https://www.imdb.com/name/nm1429471?ref_=nmls_hd
5,Jaume Balagueró,43 premios y 15 nominaciones,News (54),Talk-Show (48),https://www.imdb.com/name/nm0049371?ref_=nmls_hd
6,Carlos Saura,63 premios y 47 nominaciones en total,Documentary (62),News (51),https://www.imdb.com/name/nm0767022?ref_=nmls_hd
7,Juan Carlos Fresnadillo,15 premios y 7 nominaciones en total,Drama (24),Thriller (23),https://www.imdb.com/name/nm0294379?ref_=nmls_hd
8,Kike Maíllo,8 premios y 5 nominaciones,Animation (37),Drama (26),https://www.imdb.com/name/nm1665932?ref_=nmls_hd
9,Luis García Berlanga,27 premios y 9 nominaciones,Comedy (65),Documentary (30),https://www.imdb.com/name/nm0305557?ref_=nmls_hd
10,Pedro Almodóvar,173 premios y 222 nominaciones en total,News (135),Talk-Show (130),https://www.imdb.com/name/nm0000264?ref_=nmls_hd
11,Vicente Aranda,21 premios y 19 nominaciones,News (39),Drama (31),https://www.imdb.com/name/nm0033005?ref_=nmls_hd
12,Fernando León de Aranoa,61 premios y 46 nominaciones,News (47),Comedy (46),https://www.imdb.com/name/nm0508208?ref_=nmls_hd
13,Paco Cabezas,2 premios y 4 nominaciones,Drama (67),Fantasy (34),https://www.imdb.com/name/nm2161247?ref_=nmls_hd
14,Isabel Coixet,55 premios y 40 nominaciones,News (96),Talk-Show (77),https://www.imdb.com/name/nm0170043?ref_=nmls_hd
15,Álex de la Iglesia,34 premios y 43 nominaciones,Comedy (94),Talk-Show (79),https://www.imdb.com/name/nm0407067?ref_=nmls_hd
16,Julio Medem,38 premios y 22 nominaciones,News (26),Drama (24),https://www.imdb.com/name/nm0575523?ref_=nmls_hd
17,Juanma Bajo Ulloa,16 premios y 10 nominaciones,News (17),Talk-Show (15),https://www.imdb.com/name/nm0048056?ref_=nmls_hd
18,Paula Ortiz,7 premios y 13 nominaciones,News (15),Talk-Show (13),https://www.imdb.com/name/nm2315216?ref_=nmls_hd
19,Cesc Gay,48 premios y 40 nominaciones,Comedy (86),News (38),https://www.imdb.com/name/nm0310747?ref_=nmls_hd

In [18]:
generosdirectores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   directores  114 non-null    object
 1   premios     114 non-null    object
 2   generos1    114 non-null    object
 3   generos2    114 non-null    object
 4   urls2       114 non-null    object
dtypes: object(5)
memory usage: 4.6+ KB

In [19]:
generosdirectores.to_csv(r'C:\Users\USER\Documents\Lucía\Ironhack\Bootcamp\Proyecto_final\directoresgenero.csv')

In [21]:
tabla1= pd.read_csv('directores.csv')
tabla1

,Position,Const,Created,Modified,Description,Name,Known For,Birth Date
0,1,nm0563748,2021-11-06,2021-11-06,NaN,Achero Mañas,El Bola,1966-09-05
1,2,nm0024622,2021-11-06,2021-11-06,NaN,Alejandro Amenábar,The Others,1972-03-31
2,3,nm1291105,2021-11-06,2021-11-06,NaN,J.A. Bayona,El orfanato,1975-05-09
3,4,nm0054219,2021-11-06,2021-11-06,NaN,Juan Antonio Bardem,Calle Mayor,1922-06-02
4,5,nm1429471,2021-11-06,2021-11-06,NaN,Jaume Collet-Serra,The Shallows,1974-03-23
...,...,...,...,...,...,...,...,...
109,110,nm4209430,2021-11-06,2021-11-06,NaN,Carlos Vermut,Quién te cantará,1980-03-06
110,111,nm3427032,2021-11-06,2021-11-06,NaN,Carla Simón,Alcarràs,1986-12-22
111,112,nm1666855,2021-11-06,2021-11-06,NaN,Raúl Arévalo,Tarde para la ira,1979-11-22
112,113,nm1970178,2021-11-06,2021-11-06,NaN,Pilar Palomero,Las niñas,NaN
113,114,nm2111339,2021-11-06,2021-11-06,NaN,Borja Soler,Stockholm,NaN

In [22]:
tabla2= tabla1.rename(columns= {'Name':'directores'})
tabla2

,Position,Const,Created,Modified,Description,directores,Known For,Birth Date
0,1,nm0563748,2021-11-06,2021-11-06,NaN,Achero Mañas,El Bola,1966-09-05
1,2,nm0024622,2021-11-06,2021-11-06,NaN,Alejandro Amenábar,The Others,1972-03-31
2,3,nm1291105,2021-11-06,2021-11-06,NaN,J.A. Bayona,El orfanato,1975-05-09
3,4,nm0054219,2021-11-06,2021-11-06,NaN,Juan Antonio Bardem,Calle Mayor,1922-06-02
4,5,nm1429471,2021-11-06,2021-11-06,NaN,Jaume Collet-Serra,The Shallows,1974-03-23
...,...,...,...,...,...,...,...,...
109,110,nm4209430,2021-11-06,2021-11-06,NaN,Carlos Vermut,Quién te cantará,1980-03-06
110,111,nm3427032,2021-11-06,2021-11-06,NaN,Carla Simón,Alcarràs,1986-12-22
111,112,nm1666855,2021-11-06,2021-11-06,NaN,Raúl Arévalo,Tarde para la ira,1979-11-22
112,113,nm1970178,2021-11-06,2021-11-06,NaN,Pilar Palomero,Las niñas,NaN
113,114,nm2111339,2021-11-06,2021-11-06,NaN,Borja Soler,Stockholm,NaN

In [23]:
tabla2.to_csv('directores.csv')